# Generated by Django 5.2.11 on 2026-02-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_specialite_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="L'utilisateur a cliqué sur le lien de vérification",
                verbose_name="Email vérifié",
            ),
        ),
    ]
