# Generated by Django 5.2.11 on 2026-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_email_verified_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="laureatprofile",
            name="mentorship_areas",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Domaines de mentorat"
            ),
        ),
        migrations.AddField(
            model_name="laureatprofile",
            name="work_domain",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Domaine de travail"
            ),
        ),
        migrations.AddField(
            model_name="schoolguide",
            name="url_pdf",
            field=models.URLField(blank=True, verbose_name="URL du PDF"),
        ),
        migrations.AddField(
            model_name="user",
            name="campus",
            field=models.CharField(blank=True, max_length=100, verbose_name="Campus"),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Centres d'intérêt"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AddField(
            model_name="user",
            name="looking_for",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Je recherche"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="biographie",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Biographie"
            ),
        ),
    ]
