# Generated by Django 5.2.11 on 2026-03-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_laureatprofile_mentorship_areas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="URL Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="LinkedIn URL"
            ),
        ),
    ]
