# Generated by Django 5.2.11 on 2026-03-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_change_url_fields_to_char"),
    ]

    operations = [
        migrations.AddField(
            model_name="laureatprofile",
            name="competences",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Compétences"
            ),
        ),
        migrations.AddField(
            model_name="laureatprofile",
            name="historique",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Historique académique et professionnel",
            ),
        ),
    ]
