# Generated by Django 5.2.11 on 2026-03-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_historique_competences"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icône (FontAwesome)"
                    ),
                ),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False, verbose_name="Catégorie prédéfinie"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de compétence",
                "verbose_name_plural": "Catégories de compétences",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="laureatprofile",
            name="competences",
        ),
        migrations.RemoveField(
            model_name="laureatprofile",
            name="historique",
        ),
        migrations.AddField(
            model_name="laureatprofile",
            name="competences_legacy",
            field=models.JSONField(
                blank=True, default=list, verbose_name="[LEGACY] Compétences JSON"
            ),
        ),
        migrations.AddField(
            model_name="laureatprofile",
            name="historique_legacy",
            field=models.JSONField(
                blank=True, default=list, verbose_name="[LEGACY] Historique JSON"
            ),
        ),
        migrations.CreateModel(
            name="HistoriqueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("academic", "Formation académique"),
                            ("professional", "Expérience professionnelle"),
                            ("certification", "Certification / Diplôme"),
                            ("project", "Projet personnel"),
                            ("volunteering", "Bénévolat / Associatif"),
                            ("other", "Autre"),
                        ],
                        default="professional",
                        max_length=20,
                        verbose_name="Type d'entrée",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre / Poste"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Organisation / Entreprise",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="En cours"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "laureat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_entries",
                        to="api.laureatprofile",
                        verbose_name="Profil lauréat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée d'historique",
                "verbose_name_plural": "Entrées d'historique",
                "ordering": ["-start_date", "-order"],
            },
        ),
        migrations.CreateModel(
            name="UserCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de la compétence"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Débutant"),
                            ("intermediate", "Intermédiaire"),
                            ("advanced", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competences",
                        to="api.competencecategory",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "laureat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_competences",
                        to="api.laureatprofile",
                        verbose_name="Profil lauréat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence utilisateur",
                "verbose_name_plural": "Compétences utilisateurs",
                "ordering": ["category__order", "name"],
                "unique_together": {("laureat", "category", "name")},
            },
        ),
    ]
