# Generated by Django 6.0.1 on 2026-03-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_historique_and_competences_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityproposal",
            name="image_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="activity_proposals/",
                verbose_name="Fichier image",
            ),
        ),
    ]
