# Generated by Django 6.0.1 on 2026-03-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_activityproposal_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="votesession",
            name="candidacy_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fin appel à candidatures"
            ),
        ),
        migrations.AddField(
            model_name="votesession",
            name="candidacy_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Début appel à candidatures"
            ),
        ),
    ]
