# Generated by Django 6.0.1 on 2026-03-19 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_votesession_candidacy_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BureauPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="Titre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "requires_one_year_min",
                    models.BooleanField(
                        default=False, verbose_name="Nécessite au moins 1 an à l'école"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Poste du bureau",
                "verbose_name_plural": "Postes du bureau",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="position",
            name="bureau_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_positions",
                to="api.bureauposition",
                verbose_name="Poste du bureau",
            ),
        ),
    ]
