# Generated by Django 6.0.1 on 2026-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_bureauposition_position_bureau_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityproposal",
            name="id",
            field=models.BigAutoField(
                db_column="proposal_id",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
