# Generated by Django 6.0.1 on 2026-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_activityproposal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bureaumember",
            name="position",
            field=models.CharField(
                choices=[
                    ("SG", "Secrétaire Général"),
                    ("SGA", "Secrétaire Général Adjoint"),
                    ("sg", "Secrétaire Général"),
                    ("sga", "Secrétaire Général Adjoint"),
                    ("tresorier", "Trésorier"),
                    ("tresorier_adj", "Trésorier Adjoint"),
                    ("com", "Chargé de Communication"),
                    ("com_adj", "Chargé de Communication Adjoint"),
                    ("commissaire", "Commissaire au Compte"),
                    ("event", "Chargé des Événements"),
                    ("orga", "Chargé à l'Organisation"),
                    ("orga_adj", "Chargé à l'Organisation Adjoint"),
                    ("sport", "Chargé des Sports"),
                    ("sport_adj", "Chargé des Sports Adjoint"),
                    ("culture", "Chargé de la Culture"),
                    ("integration", "Chargé de l'Intégration"),
                ],
                max_length=50,
                verbose_name="Poste",
            ),
        ),
    ]
