# Generated by Django 5.2.11 on 2026-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_bureaumember_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="duration",
            field=models.CharField(blank=True, max_length=50, verbose_name="Durée"),
        ),
        migrations.AddField(
            model_name="activity",
            name="organizer_avatar",
            field=models.URLField(blank=True, verbose_name="Avatar de l'organisateur"),
        ),
        migrations.AddField(
            model_name="activity",
            name="organizer_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Nom de l'organisateur"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date limite d'inscription"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="niveau_etude",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Niveau d'étude"
            ),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="nom_complet",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="activityregistration",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
    ]
