# Generated by Django 5.2.11 on 2026-04-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_activity_duration_activity_organizer_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(max_length=100, verbose_name="Nom complet"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "whatsapp",
                    models.CharField(max_length=20, blank=True, null=True, verbose_name="WhatsApp" ),
                ),
                (
                    "niveau_etude",
                    models.CharField(max_length=50, verbose_name="Niveau d'étude"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmé"),
                            ("cancelled", "Annulé"),
                            ("attended", "Présent"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_registrations",
                        to="api.activity",
                        verbose_name="Activité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription invité",
                "verbose_name_plural": "Inscriptions invités",
                "ordering": ["-registered_at"],
                "unique_together": {("activity", "email")},
            },
        ),
    ]
