# Generated by Django 6.0.1 on 2026-04-15 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_guestactivityregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityproposal",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de contact"
            ),
        ),
        migrations.CreateModel(
            name="GuestActivityProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("integration", "Intégration"),
                            ("formation", "Formation"),
                            ("culture", "Culture"),
                            ("networking", "Networking"),
                            ("sport", "Sport"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "proposed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date proposée"
                    ),
                ),
                (
                    "proposed_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure proposée"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "estimated_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Participants estimés"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "additional_info",
                    models.TextField(blank=True, verbose_name="Infos supplémentaires"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="URL de l'image"),
                ),
                (
                    "image_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="activity_proposals/",
                        verbose_name="Fichier image",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("under_review", "En cours d'examen"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Examiné le"
                    ),
                ),
                (
                    "reviewer_comment",
                    models.TextField(
                        blank=True, verbose_name="Commentaire du réviseur"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guest_proposals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Examiné par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition d'activité invité",
                "verbose_name_plural": "Propositions d'activités invités",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
