# Generated by Django 6.0.2 on 2026-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_activityproposal_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(help_text='Texte de la mission (plusieurs paragraphes séparés par \n\n)')),
                ('vision', models.TextField(help_text='Texte de la vision (plusieurs paragraphes séparés par \n\n)')),
                ('valeurs', models.JSONField(default=list, help_text="Liste d'objets {title, desc}")),
            ],
            options={
                'verbose_name': 'Contenu À propos',
                'verbose_name_plural': 'Contenus À propos',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name="Valeur (ex: '500+')")),
                ('label', models.CharField(max_length=100, verbose_name="Libellé (ex: 'Lauréats')")),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('executive', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=10)),
                ('filiere', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=100)),
                ('mandat', models.CharField(max_length=20)),
                ('mission', models.TextField(max_length=500)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PracticalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('link_label', models.CharField(max_length=50)),
                ('link_url', models.URLField()),
                ('color', models.CharField(default='#172d45', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Information pratique',
                'verbose_name_plural': 'Informations pratiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'Petite 1'), (2, 'Petite 2'), (3, 'Grande')])),
            ],
            options={
                'verbose_name': 'Média École',
                'verbose_name_plural': 'Médias École',
            },
        ),
        migrations.CreateModel(
            name='StudentGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('filename', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide étudiant',
                'verbose_name_plural': 'Guides étudiants',
            },
        ),
    ]
