# Generated by Django 6.0.2 on 2026-04-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_laureatjoinrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laureatjoinrequest',
            options={'ordering': ['-submitted_at'], 'verbose_name': "Demande d'inscription lauréat", 'verbose_name_plural': "Demandes d'inscription lauréat"},
        ),
    ]
