# Generated by Django 5.0.6 on 2026-05-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_seed_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestactivityregistration',
            name='whatsapp',
        ),
    ]
