# Generated by Django 5.2.14 on 2026-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_classroom_semester_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['category', '-created_at'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('bureau', 'Membre du Bureau'), ('admin', 'Administrateur'), ('adminpromo', 'Admin de Promotion'), ('laureat', 'Lauréat')], default='student', max_length=20, verbose_name='Rôle'),
        ),
    ]
