# Generated by Django 5.2.17 on 2026-09-02 19:46

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_resource_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityproposal',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_proposals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), api.validators.validate_image_size, api.validators.validate_image_content], verbose_name='Fichier image'),
        ),
        migrations.AlterField(
            model_name='guestactivityproposal',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='activity_proposals/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), api.validators.validate_image_size, api.validators.validate_image_content], verbose_name='Fichier image'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='leaders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), api.validators.validate_image_size, api.validators.validate_image_content]),
        ),
    ]
